#ifndef EKF_MONO_SLAM_DESCRIPTOR_EXTRACTOR_TYPE_H
#define EKF_MONO_SLAM_DESCRIPTOR_EXTRACTOR_TYPE_H

enum class DescriptorExtractorType {
  BRISK,
  AKAZE,
  FAST,
  ORB,
};

#endif  // EKF_MONO_SLAM_DESCRIPTOR_EXTRACTOR_TYPE_H
