#ifndef EKF_MONO_SLAM_MAP_FEATURE_TYPE_H_
#define EKF_MONO_SLAM_MAP_FEATURE_TYPE_H_

enum class MapFeatureType {
  INVALID = 0,
  INVERSE_DEPTH,
  DEPTH
};

#endif /* EKF_MONO_SLAM_MAP_FEATURE_TYPE_H_ */
