[project]
name = "ekf_mono_slam"
version = "0.1.0"
description = "Visual Mono SLAM with 1-Point RANSAC EKF"
authors = ["Alvaro <agaona@asapp.com>"]
channels = ["conda-forge", "robostack-staging"]
platforms = ["linux-64"]

[tasks]
build = { cmd = [
  "colcon",
  "build",
  "--symlink-install",
  "--event-handler",
  "console_direct+",
  "--cmake-args",
  "-G Ninja",
  "-DPython3_EXECUTABLE=$CONDA_PREFIX/bin/python",
] }
test = { cmd = [
  "colcon",
  "test",
  "--ctest-args",
  "tests",
  "ekf_mono_slam",
  "&&",
  "./build/ekf_mono_slam/slam_test",
] }

[dependencies]
ros-humble-desktop = ">=0.10.0,<0.11"
colcon-common-extensions = ">=0.3.0,<0.4"
ninja = ">=1.12.0,<1.13"
cmake = ">=3.28.3,<3.29"
pkg-config = ">=0.29.2,<0.30"
compilers = ">=1.7.0,<1.8"
ros-humble-ament-cmake-auto = ">=1.3.7,<1.4"
spdlog = ">=1.12.0,<1.13"
clang-format = ">=18.1.3,<18.2"

[activation]
scripts = ["install/setup.sh"]
