<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>ekf_mono_slam</name>
  <version>0.1.0</version>
  <description>Visual Mono SLAM with 1-Point RANSAC EKF</description>
  <maintainer email="alvgaona@gmail.com">Alvaro J. Gaona</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>cv_bridge</depend>
  <depend>image_transport</depend>
  <depend>libopencv-dev</depend>
  <depend>eigen</depend>

  <build_depend>rosidl_default_generators</build_depend>
  <build_depend>gtest</build_depend>
  <build_depend>google-mock</build_depend>
  <exec_depend>rosidl_default_runtime</exec_depend>
  <member_of_group>rosidl_interface_packages</member_of_group>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
